export const SEMANTIC_SCHEMA_VERSION = 3;
export const SEMANTIC_EXTRACTOR_VERSION = "8";

export const ORIENTATION_ANGLE_TOLERANCE = Math.PI / 24;
export const LINE_BASELINE_TOLERANCE_RATIO = 0.65;
export const LINE_GAP_HEIGHT_RATIO = 4;
export const PARAGRAPH_GAP_MULTIPLIER = 1.8;

export const DEFAULT_MAX_CACHE_QUERY = 10;
export const MAX_SEMANTIC_CANDIDATES = 10;
